serial_comm_node:
  ros__parameters:
    file_name: "/dev/ttyUSB0"
    
land_vehicle_node:
  ros__parameters:
    rules:
      - 4.00   # Threshold Distance
      - 1.50   # Safety Distance
      - 0.60   # Vehicle Radius
      - 0.60   # Object Width 


# 0.60
# 1.00
