command_node:
  ros__parameters:
    control_unit: "keyboard" # joy, esp8266, keyboard
    file_name: "/dev/ttyUSB0"
    
land_vehicle_node:
  ros__parameters:
    rules:
      - 5.00   # Threshold Distance
      - 3.00   # Safety Distance
      - 0.60   # Vehicle Radius
      - 0.30   # Vehicle Width 
    sensor:
      - 3.0    # Max Range
      - 0.1    # Min Range


